### ISSUE TITLE
mockery doesn't work with local package

### ISSUE THREAD

**Issue by hardskulls** [vektra/mockery#727] opened 2023-10-27 20:45 UTC
PLEASE READ
-------------

go `1.21`
mockery `2.36.0`

Cleaned cache, used latest versions.
Do I have to use latest versions and clean cache everytime I use the lib?
Is it `go`'s fault or is it `mockery` specific?

Description
-------------
I dont want to use `github` path, but `mockery` doesn't work with local package.
My config is 
```yaml
packages:
  this_project:
    config:
      recursive: true
      all: true
```
When I run `mockery` I get this:
```
27 Oct 23 23:02 MSK INF Starting mockery dry-run=false version=v2.36.0
27 Oct 23 23:02 MSK INF Using config: C:\Users\ThisUser\Documents\Code\this_project\.mockery.yaml dry-run=false version=v2.36.0
27 Oct 23 23:02 MSK INF done parsing, loading dry-run=false version=v2.36.0
27 Oct 23 23:02 MSK INF done loading, visiting interface nodes dry-run=false version=v2.36.0
getting package config: unable to get map config for package: package not found in config
goroutine 1 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x5e
github.com/vektra/mockery/v2/pkg/stackerr.NewStackErr(...)
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/pkg/stackerr/stackerr.go:17
github.com/vektra/mockery/v2/pkg/stackerr.NewStackErrf({0x889780?, 0xc000092690}, {0x7c60b9?, 0xc000240940?}, {0x0?, 0x0?, 0x30?})
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/pkg/stackerr/stackerr.go:24 +0xb8
github.com/vektra/mockery/v2/pkg/config.(*Config).GetPackageConfig(0xc00010e8c0, {0x88d7c8, 0xc00065d470}, {0xc000240940, 0x40})
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/pkg/config/config.go:234 +0x425
github.com/vektra/mockery/v2/pkg/config.(*Config).ShouldGenerateInterface(0x88af80?, {0x88d7c8, 0xc00065d470}, {0xc000240940, 0x40}, {0xc00032a1b0, 0xf})
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/pkg/config/config.go:264 +0x49
github.com/vektra/mockery/v2/cmd.(*RootApp).Run(0xc00010e8c0)
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/cmd/mockery.go:261 +0x1de6
github.com/vektra/mockery/v2/cmd.NewRootCmd.func1(0xc00011ce00?, {0x793b64?, 0x4?, 0x793b68?})
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/cmd/mockery.go:46 +0x45
github.com/spf13/cobra.(*Command).execute(0xc000132600, {0xc000092090, 0x0, 0x0})
        C:/Users/ThisUser/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc000132600)
        C:/Users/ThisUser/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/ThisUser/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/vektra/mockery/v2/cmd.Execute()
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/cmd/mockery.go:104 +0x18
main.main()
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/main.go:8 +0xf

```

**Comment by LandonTClipp** [comment] 2023-10-30 18:41
Is the name of your module in `go.mod` the same as what you specified in `.mockery.yaml`?

**Comment by hardskulls** [comment] 2023-10-31 17:29
Yes

**Comment by LandonTClipp** [comment] 2023-10-31 18:32
Can you post the full results of the mockery run with debug logs?

**Comment by hardskulls** [comment] 2023-10-31 20:48
Sure.
Note that this time I used fresh, almost empty project, but result is the same.

```
31 Oct 23 23:33 MSK INF Starting mockery dry-run=false version=v2.36.0
31 Oct 23 23:33 MSK INF Using config: C:\Users\ThisUser\Documents\Code\MyCode\TestProjects\go_mockery_bug\.mockery.yaml dry-run=false version=v2.36.0
31 Oct 23 23:33 MSK DBG package cache is nil dry-run=false version=v2.36.0
31 Oct 23 23:33 MSK DBG discovering sub-packages dry-run=false package-path=go_mockery_bug version=v2.36.0
31 Oct 23 23:33 MSK DBG subdirectory has a .go file, adding this path to packages config dry-run=false package-path=go_mockery_bug path="C:\\Users\\ThisUser\\Documents\\Code\\go_mockery_bug\\application\\service\\user_service\\repository" version=v2.36.0
31 Oct 23 23:33 MSK DBG subdirectory has a .go file, adding this path to packages config dry-run=false package-path=go_mockery_bug path="C:\\Users\\ThisUser\\Documents\\Code\\go_mockery_bug\\application\\service\\user_service" version=v2.36.0
31 Oct 23 23:33 MSK DBG adding sub-package config dry-run=false package-path=go_mockery_bug sub-package="go_mockery_bug\\application/service/user_service/repository" version=v2.36.0
31 Oct 23 23:33 MSK DBG adding sub-package config dry-run=false package-path=go_mockery_bug sub-package="go_mockery_bug\\application/service/user_service" version=v2.36.0
31 Oct 23 23:34 MSK DBG found file dry-run=false file="C:\\Users\\ThisUser\\Documents\\Code\\go_mockery_bug\\application\\service\\user_service\\user.go" package=go_mockery_bug/application/service/user_service version=v2.36.0
31 Oct 23 23:34 MSK DBG found file dry-run=false file="C:\\Users\\ThisUser\\Documents\\Code\\go_mockery_bug\\main.go" package=go_mockery_bug version=v2.36.0
31 Oct 23 23:34 MSK DBG found file dry-run=false file="C:\\Users\\ThisUser\\Documents\\Code\\go_mockery_bug\\application\\service\\user_service\\repository\\user_repo.go" package=go_mockery_bug/application/service/user_service/repository version=v2.36.0
31 Oct 23 23:34 MSK INF done parsing, loading dry-run=false version=v2.36.0
31 Oct 23 23:34 MSK INF done loading, visiting interface nodes dry-run=false version=v2.36.0
getting package config: unable to get map config for package: package not found in config
goroutine 1 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x5e
github.com/vektra/mockery/v2/pkg/stackerr.NewStackErr(...)
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/pkg/stackerr/stackerr.go:17
github.com/vektra/mockery/v2/pkg/stackerr.NewStackErrf({0x1499780?, 0xc00010a690}, {0x13d60b9?, 0xc0004d9b00?}, {0x0?, 0x0?, 0x30?})
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/pkg/stackerr/stackerr.go:24 +0xb8
github.com/vektra/mockery/v2/pkg/config.(*Config).GetPackageConfig(0xc00025e000, {0x149d7c8, 0xc0004fa030}, {0xc0004d9b00, 0x3a})
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/pkg/config/config.go:234 +0x425
github.com/vektra/mockery/v2/pkg/config.(*Config).ShouldGenerateInterface(0x149af80?, {0x149d7c8, 0xc0004fa030}, {0xc0004d9b00, 0x3a}, {0xc0004b6e78, 0x8})
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/pkg/config/config.go:264 +0x49
github.com/vektra/mockery/v2/cmd.(*RootApp).Run(0xc00025e000)
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/cmd/mockery.go:261 +0x1de6
github.com/vektra/mockery/v2/cmd.NewRootCmd.func1(0xc00021a500?, {0x13a3b64?, 0x4?, 0x13a3b68?})
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/cmd/mockery.go:46 +0x45
github.com/spf13/cobra.(*Command).execute(0xc0001b2600, {0xc00011c050, 0x2, 0x3})
        C:/Users/ThisUser/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b2600)
        C:/Users/ThisUser/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/ThisUser/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/vektra/mockery/v2/cmd.Execute()
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/cmd/mockery.go:104 +0x18
main.main()
        C:/Users/ThisUser/go/pkg/mod/github.com/vektra/mockery/v2@v2.36.0/main.go:8 +0xf


```

**Comment by LandonTClipp** [comment] 2023-11-01 00:16
Okay I think I know the issue. It's coming from the fact that mockery is registering the sub package as 

    go_mockery_bug\\application/service/user_service/repository

Notice the backslash. This appears to be a bug with how mockery joins paths on Windows. I'll need a patch to my pathlib package to override the separator value, which defaults to the system path separator.

**Comment by hardskulls** [comment] 2023-11-01 11:16
Ok, glad to hear that. 
Now I wait for the patch, and close the issue if the problem is solved, right?

**Comment by LandonTClipp** [comment] 2023-11-01 13:51
Yeah this issue will be closed when the PR to fix it is merged.

**Comment by LandonTClipp** [comment] 2023-11-01 17:33
> when configuring the package using the module name configured in go.mod I get  no required module provides package(*)

This sounds like a parsing error, perhaps some required dependency is missing in your `go.mod` file.

> (I've been trying to use relative paths from the root of the project (ie ./path/to/package/to/mock, which make it fail further in the process with a getting package config: unable to get map config for package: package not found in config)

I don't believe this would ever work, packages have to be specified by their fully qualified name.

**Comment by KennyHoang-CS** [comment] 2023-12-03 07:50
Hey @LandonTClipp Having the same issue of generating local packages via mockery with the packages config file as well. I can get around this by using the deprecated mockery V2 approach for now by using the command-line and just pass the name of the interfaced to be mocked directly. 

Would this issue be fixed before mockery V3 releases?

**Comment by maard** [comment] 2024-02-05 15:40
I have the same issue as @Shastick and @KennyHoang-CS when trying to upgrade to the packages feature. When i put
```
packages:
  github.com/MyOrg/my-package
```

(the name of the package matches the name in `go.mod`), i receive

`ERR encountered error when loading package error="-: no required module provides package github.com/MyOrg/my-package; to add it:\n\tgo get github.com/MyOrg/my-package" dry-run=false version=v2.40.1`.

So i have to resort to the approach we use currently, which worked for a long time: annotate each mocked interface with `//go:generate mockery --name Name` and running `go generate ./...`.

When i compare my setup with the mockery project itself, nothing stands out, except the fact that `.mockery.yaml` in `vektra/mockery` does not have an entry for the `github.com/vektra/mockery/v2` itself, only for several sub-packages:
https://github.com/vektra/mockery/blob/4854efd1ae4dfeb13e2462bc36e3a054ee672d09/.mockery.yaml#L9

**Comment by LandonTClipp** [comment] 2024-02-13 01:24
I am not going to be able to debug these various situations. What would be more helpful is if someone could provide a reproducer for me, that way I can narrow down where the issue is.

**Closed** 2024-03-12 20:12 UTC

**Comment by rejinka** [comment] 2024-11-13 12:01
The example provided by @Edenshaw doesn't work with mockery 2.46.3 on Ubuntu (WSL) either.
