### ISSUE TITLE
Difference in whitespace with the same version.

### ISSUE THREAD

**Issue by arvenil** [vektra/mockery#516] opened 2022-11-07 18:53 UTC
Description
-------------

I run into very strange issue. When generating expecter, list of parameters in doc comment has THREE spaces instead of TWO in front of each dash.

```patch
 // GetID is a helper method to define mock.On call
-//  - _a0 context.Context
-//  - _a1 string
+//   - _a0 context.Context
+//   - _a1 string
```

I've tried:
- Different versions of mockery (homebrew and go install)
- Different versions of go
- Cleaning golang cache (-cache, -modcache, -testcache)
- Removing whole GOPATH
- Modifying source code and recompiling mockery with slightly different template

The last one lead to absolutely ridiculous discoveries where I pretty much can have ONE space or THREE, but never TWO.

Workaround for me right now is to replace `//   - ` with `//  - ` after generating mocks.

My wild guess is that dash `-` in template messes up with it as it's also used to trim white spaces.

I get THREE spaces when I have this original template:
```
// {{.MethodName}} is a helper method to define mock.On call
{{- range .Params.Params}}
//  - {{.}}
{{- end}}
```

I get ONE space if I remove one:
```
// {{.MethodName}} is a helper method to define mock.On call
{{- range .Params.Params}}
// - {{.}}
{{- end}}
```

I'm at the stage where I'm willing to open a pull request to remove that one unnecessary space - would you accept it? I know the issue seems to be on my side but I can't track it down and that one space looks totally unnecessary ;d

Mockery Version
--------

```
% mockery --version
07 Nov 22 19:40 CET INF Starting mockery dry-run=false version=v2.14.0
v2.14.0
```

Golang Version
--------------

```
kdz@dz ~ % go version
go version go1.19.3 darwin/arm64
```

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [x] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

Just run `mockery --all --exported --with-expecter` on my laptop :)

### Expected Behavior

I should have TWO white spaces.

### Actual Behavior

I have THREE white spaces.

```patch
 // GetID is a helper method to define mock.On call
-//  - _a0 context.Context
-//  - _a1 string
+//   - _a0 context.Context
+//   - _a1 string
```

**Comment by arvenil** [comment] 2022-11-08 08:58
Fresh mind in the morning. As a hygiene routine I always run `go fmt ./...`. Apparently it doesn't like those two spaces and turns them into three. Maybe it was a change when they introduced lists in documentation.

I would consider this a bug then and a proper fix would be to indeed get rid of that one space.

**Comment by vaguecoder** [comment] 2022-11-20 03:26
After #515, it is failing for `go1.18.8` linux/amd64. :confused: Is this expected behavior? 
<details>
<summary>Error Logs</summary>

```
            	           	Diff:
            	           	--- Expected
            	           	+++ Actual
            	           	@@ -51,3 +51,3 @@
            	           	 (string) (len=68) "// GenericAnonymousStructs is a helper method to define mock.On call",
            	           	- (string) (len=38) "//   - _a0 struct{Type1 TExternalIntf}",
            	           	+ (string) (len=37) "//  - _a0 struct{Type1 TExternalIntf}",
            	           	 (string) (len=314) "func (_e *RequesterGenerics_Expecter[TAny, TComparable, TSigned, TIntf, TExternalIntf, TGenIntf, TInlineType, TInlineTypeGeneric]) GenericAnonymousStructs(_a0 interface{}) *RequesterGenerics_GenericAnonymousStructs_Call[TAny, TComparable, TSigned, TIntf, TExternalIntf, TGenIntf, TInlineType, TInlineTypeGeneric] {",
            	           	@@ -100,4 +100,4 @@
            	           	 (string) (len=61) "// GenericArguments is a helper method to define mock.On call",
            	           	- (string) (len=15) "//   - _a0 TAny",
            	           	- (string) (len=22) "//   - _a1 TComparable",
            	           	+ (string) (len=14) "//  - _a0 TAny",
            	           	+ (string) (len=21) "//  - _a1 TComparable",
            	           	 (string) (len=317) "func (_e *RequesterGenerics_Expecter[TAny, TComparable, TSigned, TIntf, TExternalIntf, TGenIntf, TInlineType, TInlineTypeGeneric]) GenericArguments(_a0 interface{}, _a1 interface{}) *RequesterGenerics_GenericArguments_Call[TAny, TComparable, TSigned, TIntf, TExternalIntf, TGenIntf, TInlineType, TInlineTypeGeneric] {",
            	           	@@ -141,3 +141,3 @@
            	           	 (string) (len=59) "// GenericStructs is a helper method to define mock.On call",
            	           	- (string) (len=39) "//   - _a0 test.GenericType[TAny,TIntf]",
            	           	+ (string) (len=38) "//  - _a0 test.GenericType[TAny,TIntf]",
            	           	 (string) (len=296) "func (_e *RequesterGenerics_Expecter[TAny, TComparable, TSigned, TIntf, TExternalIntf, TGenIntf, TInlineType, TInlineTypeGeneric]) GenericStructs(_a0 interface{}) *RequesterGenerics_GenericStructs_Call[TAny, TComparable, TSigned, TIntf, TExternalIntf, TGenIntf, TInlineType, TInlineTypeGeneric] {",
            	Test:       	TestGeneratorSuite/TestGenericExpecterGenerator
            	Messages:   	The generator produced unexpected output.
FAIL
FAIL	github.com/vektra/mockery/v2/pkg	9.515s
```
</details>

Since this comes with `gofmt`, instead of working on templates, can't we just accept both 2 & 3 spaces in generated code?

**Comment by LandonTClipp** [comment] 2023-04-10 14:47
Closing this as I don't believe this is an active issue anymore? Let me know if that's not the case.

**Closed by LandonTClipp** 2023-04-10 14:47 UTC
