### ISSUE TITLE
Loader changes break vendoring

### ISSUE THREAD

**Issue by tehleach** [vektra/mockery#112] opened 2016-11-29 23:29 UTC
Just FYI:

We noticed that generating mocks on files that rely on vendored dependencies broke yesterday. Looking through this packages non built-in dependencies, I found [some changes](https://github.com/golang/tools/commit/6c803ab014286e086881c410cba381b02317423c) made to [golang.org/x/tools/go/loader](http://golang.org/x/tools/go/loader) which seem to have shifted absolute path -> relative path. I spent some time trying to make mockery work with these changes, but just ended up vendoring the old commit on [my branch](https://github.com/tehleach/mockery) for now, couldn't figure out how to get it working.

**Comment by mmcloughlin** [comment] 2016-12-03 16:41
If you're using [glide](https://github.com/Masterminds/glide), this will get you a working version of mockery:

```yaml
- package: github.com/vektra/mockery
  version: 4db903efa8f6a978c8ccee3d4f23e947af878ca9
- package: golang.org/x/tools
  version: c060f04f93f57c44284360be78bb323077183645
  subpackages:
  - go/loader
```

**Comment by nikolay-turpitko** [comment] 2016-12-06 12:35
@mmcloughlin, Thank you Michael!

For workaround it Travis build I've replaced

```
go get github.com/vektra/mockery/.../
```

with

```
- glide up
- go install github.com/letsrock-today/authkit/vendor/github.com/vektra/mockery/.../
```

**Comment by mmcloughlin** [comment] 2016-12-07 03:35
@nikolay-turpitko I'd recommend using `glide install` in your build.

**Comment by nikolay-turpitko** [comment] 2016-12-07 07:00
@mmcloughlin yes, you are right, thanks for the tip

**Comment by Franky12** [comment] 2017-01-04 12:14
Is this issue fixed?

**Comment by codeactual** [comment] 2017-01-06 06:00
@Franky12 I don't think it is.
@tehleach Can this one be closed as a duplicate of #91?

**Comment by tehleach** [comment] 2017-01-06 06:26
@codeactual I don't think so - I'm pretty certain the issue began specifically with the commit to golang.org/x/tools/go/loader that I linked in the issue originally, which happened in early November. #91 is from June so I'm thinking it's unrelated. I guess I'm not really sure what the proper convention is for duplicates, but I feel like the solution to this issue will have something to do with absolute vs relative path so I think the info / discussion here would be useful.

**Comment by codeactual** [comment] 2017-01-07 03:25
@tehleach Thanks. I took a closer look and your hunch about absolute/relative was right on AFAICT. I hope the PR fixes it for you.

**Comment by evanphx** [comment] 2017-03-07 05:04
Hopefully #117 fixed this for you, please indicate if not.

**Closed by evanphx** 2017-03-07 05:04 UTC
