### ISSUE TITLE
The latest mockery does not recognize packages in vendor directory

### ISSUE THREAD

**Issue by any1fish** [vektra/mockery#91] opened 2016-06-23 17:27 UTC
When I'm trying to generate mocks, it seems latest mockery does not go into vendor folder for some packages:

```
Generating mocks...
wrappers/static.go:7:2: could not import github.com/shawnburke/godi (cannot find package "github.com/shawnburke/godi" in any of:
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/shawnburke/godi (from $GOROOT)
    /Users/chen/project/pyramid/src/github.com/shawnburke/godi (from $GOPATH))

```

The shawnburke/godi package indeed exists in vendor folder of my project, but it seems mockery does not search inside the vendor folder.

The following version of mockery does not have this issue and generates mocks successfully, though:

```
commit 84bc9c2423f94383b2d3b3571def7f8032962664
Author: Mike Gaffney <gaffo@justin.tv>
Date:   Wed Apr 6 13:53:06 2016 -0700

    Fix recursion break in #59
```

**Comment by nathany** [comment] 2017-01-23 21:05
The issue persists. Testing on commit 53e21da5f9d000ffafde06fec5e5ab169a5c42c6.

**Comment by codeactual** [comment] 2017-01-24 02:50
@nathany Hi, Nathan. What CLI flags and golang version were involved? I'm curious if they included `-dir` and a relative path. If so, #117 might cover your use case.

**Comment by nathany** [comment] 2017-01-24 15:47
@codeactual Nope, not using `-dir`:

```
mockery -name=Service -recursive
```

```
❯ go version
go version go1.8rc2 darwin/amd64
```

**Comment by codeactual** [comment] 2017-01-24 21:37
Thanks @nathany. I was able to reproduce your `-name` and `-recursive` case in `go1.8rc2 linux/amd64`. 

It looks like the default `-dir=.` value leads to the same problem as in #117: relative paths are passed to `Parser.Parse` which are incompatible with eventual dependence on `build.Context.Import`.

@evanphx Can PR #117 get a review? It should restore out-of-the-box vendor support that's been broken since golang 1.6.

**Comment by codeactual** [comment] 2017-04-11 14:07
@nathany Is that issue now resolved in master?

**Comment by nathany** [comment] 2017-05-09 20:57
It is certainly looking through vendor when using master (e4fa38885187a4dd421cbe250b50f3fc566a087a) [go version go1.8.1 darwin/amd64].

`mockery -name=Service -recursive` (without `-dir`) is taking a very long time, and producing many messages like:

```
{project}/vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go:669:2: IPV6_MAX_MEMBERSHIPS redeclared in this block
...
{project}/vendor/golang.org/x/sys/unix/types_solaris.go:248:17: undeclared name: C
...
```

We do have `-dir` specified in our Makefile though, so that is working fine.

**Comment by codeactual** [comment] 2017-05-10 00:33
Thanks for the feedback.

My guess is that #109 is now the problem, based on the darwin/solaris mix. PR #145 should resolve it.

**Comment by evanphx** [comment] 2017-05-20 20:44
@nathany With all of @codeactual's PRs now merged, can you try again?

**Comment by nathany** [comment] 2017-05-30 22:56
@evanphx running with latest master b6f6c13c25c3f0a17724553fa01580f328158d7a [go version go1.8.3 darwin/amd64], I see the same behavior as reported in https://github.com/vektra/mockery/issues/91#issuecomment-300299192.

That said, we are currently using `-dir` and `-output` in our Makefile, which works just fine.

**Comment by codeactual** [comment] 2017-05-31 00:43
It looks like this (specifically vendor related) issue can be closed unless `cannot find package` is still coming up.

- `{project}/vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go:669:2: IPV6_MAX_MEMBERSHIPS` symptom was due to lack of build tag support. If it's still appearing, please add a note to #109.
- `{project}/vendor/github.com/mattn/go-sqlite3/error.go:14:17: undeclared name: C` symptom is separate from both the vendor and build tag support. I've documented what I've found in #161.

**Closed** 2020-05-04 01:07 UTC
