### ISSUE TITLE
go list stderr <<stat file=file.go: no such file or directory

### ISSUE THREAD

**Issue by krostar** [vektra/mockery#219] opened 2018-11-18 10:49 UTC
Hi,

I'm unable to make mockery running in the latest version.

Here is the steps I followed:
```
$>cd /Users/alexis.destrez/Work/go/src/github.com/krostar/r10k-trigger/pkg/r10kdeployer
$>ls -1
r10kdeployer.go
shell.go
shell_test.go
$>go get github.com/vektra/mockery/.../
$>$GOPATH/bin/mockery -all
go list stderr <<stat file=/Users/alexis.destrez/Work/go/src/github.com/krostar/r10k-trigger/pkg/r10kdeployer/r10kdeployer.go: no such file or directory
>>
go list stderr <<stat file=/Users/alexis.destrez/Work/go/src/github.com/krostar/r10k-trigger/pkg/r10kdeployer/shell.go: no such file or directory
>>
go list stderr <<stat file=/Users/alexis.destrez/Work/go/src/github.com/krostar/r10k-trigger/pkg/r10kdeployer/r10kdeployer.go: no such file or directory
>>
go list stderr <<stat file=/Users/alexis.destrez/Work/go/src/github.com/krostar/r10k-trigger/pkg/r10kdeployer/shell.go: no such file or directory
>>
```

I fixed it by doing:
```
$>cd $GOPATH/src/github.com/vektra/mockery
$>git checkout ea26575
$>go install ./...
$>cd /Users/alexis.destrez/Work/go/src/github.com/krostar/r10k-trigger/pkg/r10kdeployer
$>ls -1
r10kdeployer.go
shell.go
shell_test.go
$>$GOPATH/bin/mockery -all
Generating mock for: R10KDeployer in file: mocks/R10KDeployer.go
$>ls -1R
mocks
r10kdeployer.go
shell.go
shell_test.go

./mocks:
R10KDeployer.go
```

The latest commits(2be70d1) seems to introduce a regression that the commit `ea26575` does not have.

I don't know what to add here to help more on this issue, I hope it still useful.
Thanks for mockery, it's really usefull !

krostar

**Comment by YannickFricke** [comment] 2018-12-13 23:17
Thank you @krostar 
Had the same issue under Linux Mint Sylvia (based on Ubuntu Xenial)
I can confirm that the commands work

After some research with `git bisect` the first faulty commit must be 0ecc4a91a394dcd6de2535c8262674f8b14767cb

**Comment by atombender** [comment] 2018-12-13 23:30
Which Go version? The newest version uses the new `go/packages` library to read Go code, in order to be compatible with Go modules (introduces in 1.11). 

This library behaves a little differently, and I'm not sure what it does on < 1.11 with all edge cases (or indeed all edge cases with 1.11). It's quite possible that we only can support 1.11 from now on, but I'm not sure. 

It looks like you're using pre-modules `GOPATH` packages. I will see if I can reproduce it here.

**Comment by YannickFricke** [comment] 2018-12-14 20:58
@atombender 
Thank you for your comment! :)
My Go version:
```
go version go1.11.1 linux/amd64
```

**Comment by Helcaraxan** [comment] 2018-12-17 09:10
Same here: using pre-modules `GOPATH` and getting the same type of errors. 

In our case moving to modules is a no-no, but AFAIK you can definitely use `go/packages` with pre-module repos. A nice example is golangci/golangci-lint which uses `go/packages` as well.

**Comment by nilskuhn** [comment] 2019-03-18 07:04
Experiencing the same in a project using go modules. 
```
$ go version                              
go version go1.12 linux/amd64
$ mockery -version
1.0.0
```
Operating System: KDE neon 5.15
KDE Plasma Version: 5.15.2
KDE Frameworks Version: 5.55.0
Qt Version: 5.12.0
Kernel Version: 4.15.0-45-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-7600U CPU @ 2.80GHz
Memory: 15,5 GiB of RAM

**Comment by LandonTClipp** [comment] 2023-04-06 21:06
Hi, v1 is not supported anymore. Please open a new ticket if you still experience this issue in the latest version of mockery. Closing this ticket. Thanks!

**Closed by LandonTClipp** 2023-04-06 21:06 UTC
