### ISSUE TITLE
Does not handle function redeclarations in files with build tags

### ISSUE THREAD

**Issue by baranov1ch** [vektra/mockery#165] opened 2017-06-19 11:12 UTC
If there are files in package, for example, with the same function for different go versions (`// +build !go1.9`, `// +build go1.9`, etc.), mockery will fail:
```
fn redeclared in this block
other declaration of fn
```

**Comment by codeactual** [comment] 2017-06-19 22:34
@baranov1ch I wasn't able to reproduce this in two scenarios:

1. same function name in the same package, `a`, as the interface
1. same function name in the same package `b` imported by the interface's package `a`

Compiling with 1.8.2 and go1.9beta1 both WFM.

Here are the details of scenario 1 which sounds closest to what you described:

#### `./ifaces_versiontag/ifaces.go`

```
package ifaces_versiontag

type VersionBuildTags interface {
        Something() Doer
}
```

#### `./ifaces_versiontag/file1.go`

```
// +build go1.9

package ifaces_versiontag

type Doer struct{}

func Do() {}
```

####  `./ifaces_versiontag/file2.go`
```
// +build !go1.9

package ifaces_versiontag

type Doer struct{}

func Do() {
}
```

#### output

```
$ strings `which mockery` | grep 'compile go1.9beta1'
Go cmd/compile go1.9beta1
$ mockery -name VersionBuildTags -dir ./ifaces_versiontag -print` output:
// Code generated by mockery v1.0.0
package mocks

import ifaces_versiontag "github.com/codeactual/mockerytest/ifaces_versiontag"
import mock "github.com/stretchr/testify/mock"

// VersionBuildTags is an autogenerated mock type for the VersionBuildTags type
type VersionBuildTags struct {
        mock.Mock
}

// Something provides a mock function with given fields:
func (_m *VersionBuildTags) Something() ifaces_versiontag.Doer {
        ret := _m.Called()

        var r0 ifaces_versiontag.Doer
        if rf, ok := ret.Get(0).(func() ifaces_versiontag.Doer); ok {
                r0 = rf()
        } else {
                r0 = ret.Get(0).(ifaces_versiontag.Doer)
        }

        return r0
}
```

Can you help me get my test closer to what your working with?

**Comment by baranov1ch** [comment] 2017-06-27 18:26
Sure. Here is what I'm doing:
```
$ go version
go version go1.8.3 darwin/amd64

$ ls ./test/
test.go		test19.go	test_not19.go
```

`./test/test.go`

```
package test

//go:generate mockery -name=Interface -case=underscore -inpkg -testonly

type Interface interface {
  Do()
}

```

`./test/test19.go`

```
// +build go1.9

package test

func testFunc() {}
```

`./test/test_not19.go`

```
// +build !go1.9

package test

func testFunc() {}
```

`$ cd $GOPATH/github.com/baranov1ch/test-mockery-issue`

```
$ go generate
/Users/baranovich/src/tapoc-vagrant/work/go/src/github.com/baranov1ch/test-mockery-issue/test_not19.go:5:6: testFunc redeclared in this block
/Users/baranovich/src/tapoc-vagrant/work/go/src/github.com/baranov1ch/test-mockery-issue/test19.go:5:6: 	other declaration of testFunc
Error parsing file:  couldn't load packages due to errors: /Users/baranovich/src/tapoc-vagrant/work/go/src/github.com/baranov1ch/test-mockery-issue/test.go
/Users/baranovich/src/tapoc-vagrant/work/go/src/github.com/baranov1ch/test-mockery-issue/test_not19.go:5:6: testFunc redeclared in this block
/Users/baranovich/src/tapoc-vagrant/work/go/src/github.com/baranov1ch/test-mockery-issue/test19.go:5:6: 	other declaration of testFunc
Error parsing file:  couldn't load packages due to errors: /Users/baranovich/src/tapoc-vagrant/work/go/src/github.com/baranov1ch/test-mockery-issue/test19.go
/Users/baranovich/src/tapoc-vagrant/work/go/src/github.com/baranov1ch/test-mockery-issue/test_not19.go:5:6: testFunc redeclared in this block
/Users/baranovich/src/tapoc-vagrant/work/go/src/github.com/baranov1ch/test-mockery-issue/test19.go:5:6: 	other declaration of testFunc
Error parsing file:  couldn't load packages due to errors: /Users/baranovich/src/tapoc-vagrant/work/go/src/github.com/baranov1ch/test-mockery-issue/test_not19.go
Unable to find Interface in any go files under this path
test.go:3: running "mockery": exit status 1
```

Here's test package: https://github.com/baranov1ch/test-mockery-issue

**Comment by devnev** [comment] 2017-06-28 14:40
I'm encountering the same problem. The build tags below are taken from a real library that builds without issues.
```
$ find . -type f -print -exec cat {} \;
./go17.go
// +build go1.7
package versioned

func DoStuff() {}
./go16.go
// +build go1.6,!go1.7
package versioned

func DoStuff() {}
./iface.go
package versioned

type Iface interface {}
$ go version
go version go1.8.1 linux/amd64
$ mockery -name Iface 2>&1 | sed "s@$PWD@...@g"
.../go17.go:4:6: DoStuff redeclared in this block
.../go16.go:4:6:        other declaration of DoStuff
.../go17.go:4:6: DoStuff redeclared in this block
.../go16.go:4:6:        other declaration of DoStuff
.../go17.go:4:6: DoStuff redeclared in this block
.../go16.go:4:6:        other declaration of DoStuff
Error walking: couldn't load packages due to errors: .../iface.go, .../go16.go, .../go17.go
```
`mockery --help` includes the "quiet" flag added by #153 which is the current master, so my mockery seems up to date.

**Comment by codeactual** [comment] 2017-06-29 05:19
@baranov1ch Thanks for the test package.

This is a weird one. Still having trouble with it.

```
Thu 06/29 05:04:25 UTC ubuntu @ docker: 1f41eb8d341f : /var/dev/gopath/src/github.com/vektra/mockery 1054 (master=)
: git log -1
commit b6f6c13c25c3f0a17724553fa01580f328158d7a
Merge: fefd94b 8101ee5
Author: Evan Phoenix <evan@fallingsnow.net>
Date:   Mon May 22 12:38:35 2017 -0700

    Merge pull request #153 from nmiyake/quietFlag

    Add "-quiet" flag that suppresses output to stdout when set
Thu 06/29 05:04:29 UTC ubuntu @ docker: 1f41eb8d341f : /var/dev/gopath/src/github.com/vektra/mockery 1055 (master=)
: go version
go version go1.8.3 linux/amd64
Thu 06/29 05:04:34 UTC ubuntu @ docker: 1f41eb8d341f : /var/dev/gopath/src/github.com/vektra/mockery 1056 (master=)
: go install -a -v ./cmd/...
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
sync/atomic
math
sync
io
syscall
unicode/utf8
strconv
reflect
time
os
unicode
fmt
sort
bytes
strings
flag
go/token
path/filepath
bufio
go/scanner
path
regexp/syntax
go/ast
regexp
io/ioutil
net/url
text/template/parse
go/parser
log
text/template
compress/flate
hash
hash/adler32
compress/zlib
encoding/binary
go/doc
debug/dwarf
go/build
debug/elf
math/rand
math/big
container/heap
context
os/exec
text/scanner
golang.org/x/tools/go/ast/astutil
golang.org/x/tools/go/buildutil
go/constant
text/tabwriter
go/printer
go/types
go/format
golang.org/x/tools/imports
hash/crc32
compress/gzip
internal/pprof/profile
runtime/pprof/internal/protopprof
runtime/pprof
go/internal/gccgoimporter
go/internal/gcimporter
golang.org/x/tools/go/loader
go/importer
github.com/vektra/mockery/mockery
github.com/vektra/mockery/cmd/mockery
Thu 06/29 05:04:55 UTC ubuntu @ docker: 1f41eb8d341f : /var/dev/gopath/src/github.com/vektra/mockery 1057 (master=)
: ll `which mockery`
-rwxr-xr-x 1 ubuntu ubuntu 6.8M 2017-06-29 05:04 /var/dev/gopath/bin/mockery*
Thu 06/29 05:05:07 UTC ubuntu @ docker: 1f41eb8d341f : /var/dev/gopath/src/github.com/vektra/mockery 1058 (master=)
: cd $GOPATH/github.com/baranov1ch/test-mockery-issue
Thu 06/29 05:05:54 UTC ubuntu @ docker: 1f41eb8d341f : /var/dev/gopath/github.com/baranov1ch/test-mockery-issue 1067 (master=)
: git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
Thu 06/29 05:06:01 UTC ubuntu @ docker: 1f41eb8d341f : /var/dev/gopath/github.com/baranov1ch/test-mockery-issue 1069 (master=)
: go generate
Generating mock for: Interface
Thu 06/29 05:06:10 UTC ubuntu @ docker: 1f41eb8d341f : /var/dev/gopath/github.com/baranov1ch/test-mockery-issue 1070 (master=)
: ll
total 20K
drwxr-xr-x 8 ubuntu ubuntu 4.0K 2017-06-29 05:06 .git/
-rw-r--r-- 1 ubuntu ubuntu  307 2017-06-29 05:06 mock_interface_test.go
-rw-r--r-- 1 ubuntu ubuntu   50 2017-06-29 04:53 test19.go
-rw-r--r-- 1 ubuntu ubuntu  123 2017-06-29 04:53 test.go
-rw-r--r-- 1 ubuntu ubuntu   51 2017-06-29 04:53 test_not19.go
Thu 06/29 05:06:12 UTC ubuntu @ docker: 1f41eb8d341f : /var/dev/gopath/github.com/baranov1ch/test-mockery-issue 1071 (master=)
: cat mock_interface_test.go
// Code generated by mockery v1.0.0
package test

import mock "github.com/stretchr/testify/mock"

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
        mock.Mock
}

// Do provides a mock function with given fields:
func (_m *MockInterface) Do() {
        _m.Called()
}
```

I'll take another look at your (and @devnev 's cases) in a different environment soon.

**Comment by devnev** [comment] 2017-06-30 09:15
If I run everything inside an ubuntu container:
```
docker run --rm -v $PWD:/code ubuntu bash -c \
  'apt-get update && apt-get install -y git curl && \
  (curl -LSs https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz | tar -C /usr/local -xz) && \
  mkdir /go && export GOPATH=/go && export PATH=/usr/local/go/bin:/go/bin:$PATH && \
  go get -v github.com/vektra/mockery/cmd/mockery \
  && cd /code && mockery -name Iface'
```
I still get the failure output
```
/code/go17.go:4:6: DoStuff redeclared in this block
/code/go16.go:4:6:      other declaration of DoStuff
/code/go17.go:4:6: DoStuff redeclared in this block
/code/go16.go:4:6:      other declaration of DoStuff
/code/go17.go:4:6: DoStuff redeclared in this block
/code/go16.go:4:6:      other declaration of DoStuff
Error walking: couldn't load packages due to errors: /code/go16.go, /code/go17.go, /code/iface.go
```

**Comment by codeactual** [comment] 2017-07-02 00:15
@devnev I was able to reproduce your case. The problem is the missing [blank lines after the comment](https://golang.org/pkg/go/build/#hdr-Build_Constraints). It's now working for me in [Travis](https://travis-ci.org/codeactual/mockery/builds/249218514). See `165_case_1` in the logs.

> To distinguish build constraints from package documentation, a series of build constraints must be followed by a blank line.

@baranov1ch I'm not able to reproduce [your case](https://github.com/codeactual/mockery/tree/165/165_case_0/test) in [Travis](https://travis-ci.org/codeactual/mockery/builds/249218514). See `165_case_0` in the logs. Does your real package have the required blank lines? If not, I'm at a loss at this point.

**Comment by LandonTClipp** [comment] 2020-05-04 01:15
Closing historic ticket. Please open a new one if you still have issues.

**Closed by LandonTClipp** 2020-05-04 01:15 UTC
