### ISSUE TITLE
Mocks referencing unexported types

### ISSUE THREAD

**Issue by DeadlySurgeon** [vektra/mockery#426] opened 2021-12-20 19:32 UTC
There seems to be an argument `--exported` for `Generates public mocks for private interfaces` which I'm assuming means for unexported types? Well this is ~defaulted~ stuck on, which leads to the issue that mockery generates code that does not work as it references unexported structs.

Current version: `v2.9.4`
Command: `mockery --all --keeptree`

Do you guys have any suggestions on how to fix this? Is the problem that we use `--all` instead of specifying each individual package?

**Comment by LandonTClipp** [comment] 2022-01-25 02:27
The flag is boolean so you can assign it `--exported=False` (which should be the default) or `--exported=True`. I'm surprised it's stuck on for you though. Could you elaborate on an example?

**Closed** 2023-04-25 20:21 UTC

**Comment by rubenhazelaar** [comment] 2024-04-10 11:20
In version v2.42.1 this flag does not work so I cannot exclude private interfaces. `exclude-regex` also does not seem to work as it seems to be case insensitive (while Golang regex are not by default).

**Comment by nvx** [comment] 2024-07-05 03:22
I ran into the same issue, to save  time for the next person stumbling upon this ticket. The issue isn't case sensitivity but rather if you're not using an anchor in the regex it can appear like it is:

For example with the interfaces `FooBar`, `fooBar` and `foobar` and `include-regex: '[A-Z].+'` you get mocks generated for `FooBar` and `fooBar` but not `foobar`, meanwhile `include-regex: '^[A-Z].+'` will only generate a mock for `FooBar` which is probably what was intended.
