### ISSUE TITLE
Inlined interfaces

### ISSUE THREAD

**Issue by nikolaydubina** [vektra/mockery#531] opened 2023-01-21 03:42 UTC
Description
-------------

### Purpose

Avoid declaring non exported upstream interfaces as separate types just so they can be mocked.  

### Details

https://go.dev/play/p/Bt74sBt01Yl

```go
package main

import "fmt"

// go generate mockery Employee.address

// struct with interface
type Employee struct {
	address interface {
		StreetName() string
		BlockNumber() int
	}
}

// constructor with inlined interface
func NewEmployee(
	address interface {
		StreetName() string
		BlockNumber() int
	},
) Employee {
	return Employee{address: address}
}

// concerete upstream
type HumanAddress struct {
	streetName  string
	blockNumber int
}

func (h HumanAddress) StreetName() string { return h.streetName }

func (h HumanAddress) BlockNumber() int { return h.blockNumber }

func main() {
	e := NewEmployee(HumanAddress{streetName: "some-street", blockNumber: 11})
	fmt.Printf("%#v", e)
}
```

**Comment by nikolaydubina** [comment] 2023-01-21 03:46
I think I can implement this, if no takers!

**Comment by LandonTClipp** [comment] 2023-02-03 23:09
Can you create a proposal of how this would be implemented? Mockery would need to generate some named mock implementation of the inlined interface. I fear whatever implementation you have is going to be kind of messy, but I'm open to hear what you think.

**Comment by nikolaydubina** [comment] 2023-02-04 01:37
I see, so the concern here is that mockery does not have suitable
abstractions for this? ok! noted.

I did not look into code yet. I think if it is fast enough to hack, will
make PR. But if lots of work, then will ping you guys here again.

Cheers ! 🤝

**Comment by LandonTClipp** [comment] 2023-06-16 15:15
The problem is moreso that mockery searches a package's global scope for named interface types. If an interface definition lies inline a function signature, mockery would then need to also inspect the function signature of every top-level function. It would then need to also assign a name to that interface. It's not an impossible task, but it's not as simple as you might think.

**Comment by LandonTClipp** [comment] 2023-11-20 21:26
Going to close this as we won't be implementing it.

**Closed by LandonTClipp** 2023-11-20 21:26 UTC
