### ISSUE TITLE
Release v2.10.1 hangs on Starting mockery dry-run=false version=v2.10.1

### ISSUE THREAD

**Issue by DillonStreator** [vektra/mockery#442] opened 2022-03-31 17:05 UTC
Noted when running `mockery --all --inpackage --case snake`

**Comment by DillonStreator** [comment] 2022-03-31 17:07
resolved for now by pinning previous version
`go install github.com/vektra/mockery/v2@v2.10.0`

**Comment by LandonTClipp** [comment] 2022-04-01 18:27
I think I know where this might be coming from. My suspicion isn't that it's hanging, but that it's taking a lot longer than normal. Probably from this: https://github.com/vektra/mockery/commit/4e181be712c853258e64b29a9797f5f596661449

Please try v2.10.2, if that does work I will revert the above commit.

**Comment by Tochemey** [comment] 2022-04-01 22:53
Yeah I have observed it takes longer than before to generate the mocks.
<img width="476" alt="image" src="https://user-images.githubusercontent.com/1633645/161351967-f56c97ce-f182-47c8-b022-ed8d1c6e0554.png">

**Comment by Tochemey** [comment] 2022-04-01 22:57
At times it does hang even the lastest release.

**Comment by taylow** [comment] 2022-04-02 11:05
I am having the same issue on `darwin/arm64` (Apple M1) running `mockery --all --keeptree` and have noticed the memory usage just keeps growing.

<img width="269" alt="image" src="https://user-images.githubusercontent.com/19749421/161380297-10e608f9-144a-4174-82e7-3d19e7cddd99.png">

**Comment by ludusrusso-rc** [comment] 2022-04-04 15:17
Same here

**Comment by LandonTClipp** [comment] 2022-04-07 23:44
Folks can you try the latest release, I have reverted a change that I believed was causing the runtime issue. @emmanuel099 is showing a list of versions that work: https://github.com/vektra/mockery/pull/444

**Comment by taylow** [comment] 2022-04-08 08:45
Just installed 2.10.4 and have a new issue, is there a known fix for this error?

<img width="533" alt="image" src="https://user-images.githubusercontent.com/19749421/162399833-ad00158b-14c4-47b2-a841-9313efc3ae6d.png">

**Comment by LandonTClipp** [comment] 2022-04-08 14:46
@taylow could you provide a reproducer for this issue?

**Comment by taylow** [comment] 2022-04-11 09:48
@LandonTClipp happy to provide as much info as I can!

My current setup is:
- `go version go1.18 darwin/arm64`
- Mockery version `v2.10.4` installed via Brew
- I'm using an M1 Mac `darwin/arm64`
- I'm running the command `make mocks` via a Makefile, which calls `mockery --all --keeptree`
- I currently have Mocks that are outdated which need regenerating

If there is anything else you need/could help here please let me know!

**Comment by LandonTClipp** [comment] 2022-04-11 17:42
Thanks @taylow . Could you provide a reproducible example of this error happening? We have various matrix testing for Go versions and OS environments which haven't caught this, so I would love to fix this issue if we can isolate where it's coming from.

**Comment by taylow** [comment] 2022-04-12 13:19
Simply importing the package causes the same error

```go
import _ "github.com/samber/lo"
```

**Comment by emmanuel099** [comment] 2022-04-12 18:35
@LandonTClipp I think that we have two different issues. Mockery cannot create mocks for interfaces with generics vs. mockery fails because of generics unrelated to the mocked interface. The first issue requires additional code in mockery, whereas the second is definitely a bug IMHO:
```
package test

import _ "github.com/samber/lo" // mock generation works without this line

type Requester interface {
	Get(path string) (string, error)
}
```

This bug can either be fixed by adding `packages.NeedDeps` which introduces serve performance and memory problems, or by https://github.com/reillywatson/tools/commit/50e5cab0be89becf08e0f6b9d9337d5e8f82f708 which hopefully lands in `x/tools` soon.

**Comment by LandonTClipp** [comment] 2022-04-19 15:24
Closing this issue, please let me know if anyone is having any further issues.

**Closed by LandonTClipp** 2022-04-19 15:24 UTC

**Comment by mikegleasonjr** [comment] 2022-11-15 20:18
Still have the `Unexpected package creation during export data loading` on v2.15.0 from time to time
