### ISSUE TITLE
mock generation fails if another package exists in the same directory as the package that contains the interface

### ISSUE THREAD

**Issue by tescherm** [vektra/mockery#77] opened 2016-04-27 17:55 UTC
For example, if I have a directory structure similar to:

```
/client/client.go
/client/client_test.go
```

Where `client.go` is in the `client` package and `client_test.go` is in the `client_test` package, I see the following error when generating a mock:

```
Error parsing file:  client_test.go:3:1: package client_test; expected client
```

The current workaround is to temporarily delete the `*_test` package before running mockery to generate the mock.

**Comment by khyew** [comment] 2016-05-16 21:32
I am having the same problem. I suspect that this is related to https://github.com/vektra/mockery/issues/73 and may be caused by the fix in response to https://github.com/vektra/mockery/issues/70

Reverting to mockvery version 130a05e is another workaround.

**Comment by tescherm** [comment] 2016-06-07 22:10
Any thoughts wrt a fix? If not I'll try to see if I can fix it in a fork.

**Comment by xeger** [comment] 2016-07-05 22:02
I've coded up a potential fix to this issue that works for all of my cases; see #95 for more information.

**Comment by IvanMalison** [comment] 2016-07-05 23:49
@xeger did you check out my pull request?

**Comment by xeger** [comment] 2016-07-06 00:18
Hmm; that wouldn't be worthwhile alone given the way I use mocks and tests (i.e. I only mock "real" interfaces), but it seems you've made a number of other improvements too. Given how brittle parsing and generating is, I'm going to try your branch and see how far I can get.

**Comment by atombender** [comment] 2016-08-30 21:16
Can we get a fix for this? Using `_test` for test packages is an established Go convention, and it breaks Mockery. Having to move away the files before every `go generate` is pretty awful.

**Comment by xeger** [comment] 2016-08-30 21:56
@atombender I ended up writing my own mock generator (since I also ended up using a different mock framework) but I did add Mockery support to my generator since it aided the transition.

https://github.com/xeger/mongoose uses golang's Loader and should be able to parse any set of files that the compiler could. It's also got a fairly small codebase, and perhaps most importantly, its maintainer is paying active attention and will happily fix your bugs. ;-)

**Comment by IvanMalison** [comment] 2016-08-30 21:57
@atombender Check out my branch! I really want to get that merged!

**Comment by xeger** [comment] 2016-08-30 23:34
@IvanMalison's fix may also address #96. Personally, I've given up on Mockery at this point, with three open showstoppers that haven't been addressed after three months. :( I'd much rather _not_ have rolled my own generator, but the work is done; if either of you feel inclined to use it, I'll be happy to fix any bugs you encounter, and/or flesh out the docs to your liking.

**Comment by atombender** [comment] 2016-08-31 00:59
@evanphx Can we get this or @IvanMalison's commit merged, please? It's been almost six months.

**Comment by IvanMalison** [comment] 2016-08-31 04:35
@atombender @xeger @tescherm 

I hat to resort to this type of measure, but I'd be open to maintaining a fork of mockery on my remote, with the import paths changed. It doesn't seem like this is being actively maintained any longer.

**Closed** 2016-10-03 17:09 UTC

**Comment by atombender** [comment] 2016-10-03 17:13
Thanks, @evanphx.
